module.exports = {
    // type: 'sqlite',
    // database: 'db.sql',
    type: 'postgres',
    host: '127.0.0.1',
    port: 5432,
    database: 'rant',
    username: 'rant',
    password: '123456',
    logging: true,
    dropSchema: true,
    synchronize: true,
    entityPrefix: 't_',
    // cache: {
    //     type: 'redis',
    //     options: {
    //         host: '127.0.0.1',
    //         port: 6379,
    //     },
    // },
    entities: [__dirname + '/**/*.entity{.ts,.js}'],
    migrations: [],
    subscribers: [__dirname + '/**/*.subscriber{.ts,.js}'],
    seeds: ['/**/*.seed.ts'],
    factories: ['/**/*.factory.ts'],
};
