export const BULL_MODULE_QUEUE = Symbol('BULL_MODULE_QUEUE');
export const BULL_MODULE_QUEUE_PROCESS = Symbol('BULL_MODULE_QUEUE_PROCESS');
export const BULL_MODULE_ON_QUEUE_EVENT = Symbol('BULL_MODULE_ON_QUEUE_EVENT');
